"""Application settings.

All configuration enters the system here, through environment variables with
the ``SC__`` prefix and ``__`` as the nesting delimiter, for example
``SC__APP_DB__DSN=postgresql://...``. A ``.env`` file in the working directory
is read in development. Nothing else in the codebase should call
``os.environ`` for configuration.

Later phases add one sub-model per concern (``odoo``, ``mail``, ``llm``,
``langfuse``) so that validation happens once, at startup.
"""

from __future__ import annotations

import os
from functools import lru_cache
from os import PathLike
from typing import Any, Literal

from dotenv import dotenv_values
from pydantic import BaseModel, ConfigDict, Field, PostgresDsn, RedisDsn, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

Environment = Literal["dev", "test", "staging", "prod"]
LogLevel = Literal["TRACE", "DEBUG", "INFO", "SUCCESS", "WARNING", "ERROR", "CRITICAL"]


class _Section(BaseModel):
    """Base for nested settings sections.

    ``validate_default=True`` makes pydantic parse default strings into their
    declared types (``PostgresDsn``, ``RedisDsn``), so a default is validated
    exactly like an environment value.
    """

    model_config = ConfigDict(validate_default=True, extra="forbid")


class AppDbCfg(_Section):
    """Connection to the application database (checkpoints, cases, jobs)."""

    dsn: PostgresDsn = Field(default="postgresql://app:app@localhost:15432/app")  # type: ignore[assignment]
    pool_min: int = Field(default=1, ge=0)
    pool_max: int = Field(default=10, ge=1)
    migrations_dir: str = "migrations"


class RedisCfg(_Section):
    """Redis is used for locks and pub/sub only; nothing durable lives there."""

    dsn: RedisDsn = Field(default="redis://localhost:6379/0")  # type: ignore[assignment]


class OdooCfg(_Section):
    """Connection to Odoo as the technical bot user (JSON-RPC, API key)."""

    url: str = "http://localhost:8069"  # inside compose: http://odoo:8069
    db: str = "scai"
    login: str = "sc_agent_bot"
    api_key: SecretStr = SecretStr("")  # generated by `just odoo-apikey`
    timeout_seconds: float = Field(default=30.0, gt=0)
    max_retries: int = Field(default=3, ge=0)
    # Sent in every call's context. Leave lang empty to use the bot user's
    # language: Odoo rejects a context language that is not installed.
    lang: str = ""
    tz: str = "America/Lima"

    @property
    def configured(self) -> bool:
        return bool(self.api_key.get_secret_value())


MailAuthMode = Literal["delegated", "application"]


class MailCfg(_Section):
    """Microsoft Graph access to the purchasing mailbox.

    ``delegated`` (development): a personal Outlook.com account signs in once
    with the device-code flow; refresh tokens are cached in the app database.
    ``application`` (production, phase 10): client credentials against the
    company tenant, restricted to one shared mailbox.
    """

    auth_mode: MailAuthMode = "delegated"
    client_id: str = ""
    authority: str = "https://login.microsoftonline.com/consumers"
    tenant_id: str = ""  # application mode only
    client_secret: SecretStr = SecretStr("")  # application mode only
    mailbox: str = "me"  # "me" in delegated mode, an address in application mode
    poll_interval_minutes: int = Field(default=30, ge=1)
    scopes: list[str] = ["Mail.Read", "Mail.ReadWrite", "Mail.Send", "User.Read"]
    pdf_max_pages: int = Field(default=20, ge=1)
    pdf_max_bytes: int = Field(default=10_000_000, ge=1)

    @property
    def configured(self) -> bool:
        if not self.client_id:
            return False
        if self.auth_mode == "application":
            return bool(self.tenant_id and self.client_secret.get_secret_value() and self.mailbox)
        return True


class LlmCfg(_Section):
    """Model assignment. Providers and model capabilities live in ``sc_core/llm/models.yaml``.

    ``model`` maps an agent name (upper-case, e.g. ``SUPPLIER_COMMS``) to a
    model name from the registry: ``SC__LLM__MODEL__SUPPLIER_COMMS=gpt-5.4``.
    """

    default_model: str = "deepseek-v4-flash"
    model: dict[str, str] = {}
    timeout_seconds: float = Field(default=120.0, gt=0)
    max_retries: int = Field(default=2, ge=0)
    # Per-run budget defaults; agents may lower them, never raise them.
    budget_max_input_tokens: int = Field(default=400_000, ge=1)
    budget_max_output_tokens: int = Field(default=60_000, ge=1)
    budget_max_usd: float = Field(default=2.0, gt=0)
    record_mode: Literal["off", "record", "replay"] = "off"  # test fixtures, see llm/testing.py

    def model_for(self, agent_name: str) -> str:
        # Environment keys arrive lower-cased from pydantic-settings; compare case-insensitively.
        wanted = agent_name.lower()
        for key, value in self.model.items():
            if key.lower() == wanted:
                return value
        return self.default_model


class LangfuseCfg(_Section):
    """Self-hosted Langfuse (or Langfuse Cloud) for traces, prompts and datasets."""

    enabled: bool = True
    host: str = "http://localhost:3000"
    public_key: str = ""
    secret_key: SecretStr = SecretStr("")
    prompt_cache_seconds: int = Field(default=300, ge=0)
    mask_inputs: bool = False  # redact email text from traces (phase 10 decision)

    @property
    def configured(self) -> bool:
        return self.enabled and bool(self.public_key and self.secret_key.get_secret_value())


class HttpCfg(_Section):
    """HTTP server and middleware settings shared by every service."""

    host: str = "0.0.0.0"
    port: int = Field(default=8000, ge=1, le=65535)
    max_request_bytes: int = Field(default=1_048_576, ge=1)  # 1 MiB: JSON events and webhooks
    enable_hsts: bool = False  # only behind TLS (phase 10)
    access_log: bool = False  # request logging is done by our middleware, not uvicorn


class Settings(BaseSettings):
    """Root settings object.

    Every service constructs exactly one instance (see :func:`get_settings`)
    and passes it explicitly to the components that need it.
    """

    model_config = SettingsConfigDict(
        env_prefix="SC__",
        env_nested_delimiter="__",
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    service_name: str = Field(default="unnamed", min_length=1)
    environment: Environment = "dev"
    log_level: LogLevel = "INFO"
    log_json: bool | None = Field(
        default=None,
        description="Force JSON logs on/off. When unset, JSON is used outside 'dev'.",
    )
    timezone: str = "America/Lima"

    http: HttpCfg = Field(default_factory=HttpCfg)
    app_db: AppDbCfg = Field(default_factory=AppDbCfg)
    redis: RedisCfg = Field(default_factory=RedisCfg)
    odoo: OdooCfg = Field(default_factory=OdooCfg)
    mail: MailCfg = Field(default_factory=MailCfg)
    llm: LlmCfg = Field(default_factory=LlmCfg)
    langfuse: LangfuseCfg = Field(default_factory=LangfuseCfg)

    def __init__(self, **values: Any) -> None:
        # pydantic-settings reads .env only for its own SC__ fields. Provider API
        # keys (DEEPSEEK_API_KEY, OPENAI_API_KEY) are looked up by name in the
        # environment by sc_core.llm.registry, so on the host they must be
        # exported from the same file. Docker passes env_file, so this is a no-op there.
        env_file = values.get("_env_file", ".env")
        if env_file:
            load_env_file(env_file)
        super().__init__(**values)

    @property
    def is_dev(self) -> bool:
        return self.environment == "dev"

    @property
    def use_json_logs(self) -> bool:
        return self.log_json if self.log_json is not None else not self.is_dev


def load_env_file(path: str | PathLike[str] = ".env") -> None:
    """Export the non-``SC__`` entries of ``path`` (provider API keys) into ``os.environ``.

    ``SC__*`` values are left to pydantic-settings so ``Settings(_env_file=None)``
    keeps isolating tests from the developer's ``.env``. Existing variables win.
    """
    for key, value in dotenv_values(path).items():
        if value is not None and not key.startswith("SC__") and key not in os.environ:
            os.environ[key] = value


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Return the process-wide settings, built once from the environment."""
    return Settings()


def reset_settings_cache() -> None:
    """Forget the cached settings. Intended for tests that mutate the environment."""
    get_settings.cache_clear()
