"""Application settings.

All configuration enters the system here, through environment variables with
the ``SC__`` prefix and ``__`` as the nesting delimiter, for example
``SC__APP_DB__DSN=postgresql://...``. A ``.env`` file in the working directory
is read in development. Nothing else in the codebase should call
``os.environ`` for configuration.

Later phases add one sub-model per concern (``odoo``, ``mail``, ``llm``,
``langfuse``) so that validation happens once, at startup.
"""

from __future__ import annotations

import os
from functools import lru_cache
from os import PathLike
from typing import Any, Literal

from dotenv import dotenv_values
from pydantic import BaseModel, ConfigDict, Field, PostgresDsn, RedisDsn, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

Environment = Literal["dev", "test", "staging", "prod"]
LogLevel = Literal["TRACE", "DEBUG", "INFO", "SUCCESS", "WARNING", "ERROR", "CRITICAL"]


class _Section(BaseModel):
    """Base for nested settings sections.

    ``validate_default=True`` makes pydantic parse default strings into their
    declared types (``PostgresDsn``, ``RedisDsn``), so a default is validated
    exactly like an environment value.
    """

    model_config = ConfigDict(validate_default=True, extra="forbid")


class AppDbCfg(_Section):
    """Connection to the application database (checkpoints, cases, jobs)."""

    dsn: PostgresDsn = Field(default="postgresql://app:app@localhost:15432/app")  # type: ignore[assignment]
    pool_min: int = Field(default=1, ge=0)
    pool_max: int = Field(default=10, ge=1)
    migrations_dir: str = "migrations"


class RedisCfg(_Section):
    """Redis is used for locks and pub/sub only; nothing durable lives there."""

    dsn: RedisDsn = Field(default="redis://localhost:6379/0")  # type: ignore[assignment]


class OdooCfg(_Section):
    """Connection to Odoo as the technical bot user (JSON-RPC, API key)."""

    url: str = "http://localhost:8069"  # inside compose: http://odoo:8069
    # Where a person's browser reaches Odoo (links in the Control Tower and in notes);
    # empty = the same as ``url``. Inside compose: http://localhost:8069.
    public_url: str = ""
    db: str = "scai"
    login: str = "sc_agent_bot"
    api_key: SecretStr = SecretStr("")  # generated by `just odoo-apikey`
    timeout_seconds: float = Field(default=30.0, gt=0)
    max_retries: int = Field(default=3, ge=0)
    # Sent in every call's context. Leave lang empty to use the bot user's
    # language: Odoo rejects a context language that is not installed.
    lang: str = ""
    tz: str = "America/Lima"

    @property
    def configured(self) -> bool:
        return bool(self.api_key.get_secret_value())

    @property
    def browser_url(self) -> str:
        return (self.public_url or self.url).rstrip("/")


MailAuthMode = Literal["delegated", "application"]


class MailCfg(_Section):
    """Microsoft Graph access to the purchasing mailbox.

    ``delegated`` (development): a personal Outlook.com account signs in once
    with the device-code flow; refresh tokens are cached in the app database.
    ``application`` (production, phase 10): client credentials against the
    company tenant, restricted to one shared mailbox.
    """

    auth_mode: MailAuthMode = "delegated"
    client_id: str = ""
    authority: str = "https://login.microsoftonline.com/consumers"
    tenant_id: str = ""  # application mode only
    client_secret: SecretStr = SecretStr("")  # application mode only
    mailbox: str = "me"  # "me" in delegated mode, an address in application mode
    poll_interval_minutes: int = Field(default=30, ge=1)
    scopes: list[str] = ["Mail.Read", "Mail.ReadWrite", "Mail.Send", "User.Read"]
    pdf_max_pages: int = Field(default=20, ge=1)
    pdf_max_bytes: int = Field(default=10_000_000, ge=1)

    @property
    def configured(self) -> bool:
        if not self.client_id:
            return False
        if self.auth_mode == "application":
            return bool(self.tenant_id and self.client_secret.get_secret_value() and self.mailbox)
        return True


class LlmCfg(_Section):
    """Model assignment. Providers and model capabilities live in ``sc_core/llm/models.yaml``.

    ``model`` maps an agent name (upper-case, e.g. ``SUPPLIER_COMMS``) to a
    model name from the registry: ``SC__LLM__MODEL__SUPPLIER_COMMS=gpt-5.4``.
    """

    default_model: str = "deepseek-v4-flash"
    model: dict[str, str] = {}
    timeout_seconds: float = Field(default=120.0, gt=0)
    max_retries: int = Field(default=2, ge=0)
    # Per-run budget defaults; agents may lower them, never raise them.
    budget_max_input_tokens: int = Field(default=400_000, ge=1)
    budget_max_output_tokens: int = Field(default=60_000, ge=1)
    budget_max_usd: float = Field(default=2.0, gt=0)
    record_mode: Literal["off", "record", "replay"] = "off"  # test fixtures, see llm/testing.py

    def model_for(self, agent_name: str) -> str:
        # Environment keys arrive lower-cased from pydantic-settings; compare case-insensitively.
        wanted = agent_name.lower()
        for key, value in self.model.items():
            if key.lower() == wanted:
                return value
        return self.default_model


class LangfuseCfg(_Section):
    """Self-hosted Langfuse (or Langfuse Cloud) for traces, prompts and datasets."""

    enabled: bool = True
    host: str = "http://localhost:3000"
    # Where a person's browser reaches Langfuse (trace links); empty = ``host``.
    public_url: str = ""
    public_key: str = ""
    secret_key: SecretStr = SecretStr("")
    prompt_cache_seconds: int = Field(default=300, ge=0)
    mask_inputs: bool = False  # redact email text from traces (phase 10 decision)

    @property
    def configured(self) -> bool:
        return self.enabled and bool(self.public_key and self.secret_key.get_secret_value())

    @property
    def browser_url(self) -> str:
        return (self.public_url or self.host).rstrip("/")


class EventsCfg(_Section):
    """Service-to-director events (mail_sync, scheduler, Odoo webhooks).

    Every event is POSTed with an HMAC-SHA256 signature over the body so the
    director only accepts events from processes that hold the shared secret.
    """

    signing_secret: SecretStr = SecretStr("")
    director_url: str = "http://localhost:8010"  # inside compose: http://director:8000
    timeout_seconds: float = Field(default=10.0, gt=0)
    max_attempts: int = Field(default=3, ge=1)
    backoff_seconds: float = Field(default=0.5, ge=0)

    @property
    def configured(self) -> bool:
        return bool(self.signing_secret.get_secret_value())


class MailSyncCfg(_Section):
    """The inbox poller. The 30-minute cadence itself lives in ``scheduler``."""

    page_size: int = Field(default=50, ge=1, le=500)
    lock_ttl_seconds: int = Field(default=25 * 60, ge=1)
    url: str = "http://localhost:8011"  # inside compose: http://mail_sync:8000


class SchedulerCfg(_Section):
    """Cron table. Crons are five-field crontab strings evaluated in ``Settings.timezone``."""

    mail_sync_cron: str = "*/30 * * * *"
    po_followups_cron: str = "0 9 * * 1-5"
    inventory_planning_cron: str = "0 6 * * *"
    supplier_performance_cron: str = "0 7 * * 1"
    dispatch_timeout_seconds: float = Field(default=600.0, gt=0)


class SupplierCommsCfg(_Section):
    """The supplier communications agent."""

    # How Odoo reaches this agent for approval callbacks (inside compose: http://supplier_comms:8000).
    public_url: str = "http://localhost:8013"
    # Odoo partner ids whose emails go out without a human approval. Default: nobody.
    auto_send_partner_ids: list[int] = []
    max_attachment_chars: int = Field(default=12_000, ge=0)


class A2aCfg(_Section):
    """Agent-to-agent calls (director -> agents). Bearer token on every call.

    ``token`` empty means "use SC__EVENTS__SIGNING_SECRET", so one secret is
    enough on a laptop; production sets a distinct token.
    """

    token: SecretStr = SecretStr("")
    timeout_seconds: float = Field(default=300.0, gt=0)  # a graph run may take a while
    max_concurrent: int = Field(default=4, ge=1)  # runs in flight per agent (director side)
    # Where the director reaches each agent (inside compose: http://<service>:8000).
    supplier_comms_url: str = "http://localhost:8013"
    inventory_planning_url: str = "http://localhost:8014"


class DirectorCfg(_Section):
    """Orchestrator policy: follow-up cadence, escalation thresholds, per-order locking."""

    rfq_no_reply_days: list[int] = [3, 7]  # follow_up after these days of silence, then escalate
    po_eta_request_before_days: int = Field(default=5, ge=0)  # ask to confirm the date this early
    po_late_days: list[int] = [1, 4]  # past date_planned: request_eta, then escalate
    approval_stale_days: int = Field(default=2, ge=0)  # remind the approver
    approval_expire_days: int = Field(default=7, ge=0)  # expire the approval, escalate the case
    lock_ttl_seconds: int = Field(default=900, ge=1)  # one run per order at a time
    lock_wait_seconds: float = Field(default=120.0, ge=0)  # how long an event waits for the lock
    max_actions_per_run: int = Field(
        default=20, ge=1
    )  # follow-up job: emails + escalations per run
    reconcile_since_days: int = Field(default=3, ge=0)  # missed confirmations looked back this far


class PlanningCfg(_Section):
    """Inventory planning agent: what to plan and with which defaults."""

    history_days: int = Field(default=730, ge=60)  # demand history read from Odoo
    product_category: str = ""  # only products under this category path; empty = all plannable
    warehouse_code: str = ""  # empty = the first warehouse
    service_level: float = Field(default=0.95, gt=0.5, lt=1.0)  # default when no class param
    review_period_days: int = Field(default=7, ge=1)  # the daily plan covers a week of orders
    max_coverage_days: int = Field(default=120, ge=1)  # overstock beyond this
    lead_time_sigma_ratio: float = Field(
        default=0.25, ge=0
    )  # sigma_LT = ratio x delay until phase 9
    # Where Odoo reaches this agent for approval callbacks (inside compose: the service name).
    public_url: str = "http://localhost:8014"


class UiCfg(_Section):
    """The Control Tower (phase 8): sessions and the static bundle."""

    jwt_secret: SecretStr = SecretStr("")  # empty = reuse SC__EVENTS__SIGNING_SECRET
    jwt_ttl_minutes: int = Field(default=480, ge=5)
    login_rate_per_minute: int = Field(default=5, ge=1)
    static_dir: str = "frontend/control-tower/dist"  # served under / when it exists
    sse_heartbeat_seconds: float = Field(default=15.0, gt=0)  # keeps /api/stream alive
    # Where a person's browser opens the Control Tower (links in Odoo notes and To-Dos).
    public_url: str = "http://localhost:8010"


class AgentsCfg(_Section):
    """Shared by every LangGraph agent: who approves and how long they get."""

    approver_user_id: int = Field(default=2, ge=1)  # Odoo demo: 2 = Administrator
    approval_deadline_days: int = Field(default=2, ge=0)
    max_tool_rounds: int = Field(default=6, ge=1)  # model <-> tools loop cap per node
    # Language of what people read (explanations, summaries, approval titles, notes, the UI).
    # Emails follow the supplier's Odoo language and fall back to this. Internals stay English.
    language: Literal["en", "es"] = "en"


class HttpCfg(_Section):
    """HTTP server and middleware settings shared by every service."""

    host: str = "0.0.0.0"
    port: int = Field(default=8000, ge=1, le=65535)
    max_request_bytes: int = Field(default=1_048_576, ge=1)  # 1 MiB: JSON events and webhooks
    enable_hsts: bool = False  # only behind TLS (phase 10)
    access_log: bool = False  # request logging is done by our middleware, not uvicorn


class Settings(BaseSettings):
    """Root settings object.

    Every service constructs exactly one instance (see :func:`get_settings`)
    and passes it explicitly to the components that need it.
    """

    model_config = SettingsConfigDict(
        env_prefix="SC__",
        env_nested_delimiter="__",
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    service_name: str = Field(default="unnamed", min_length=1)
    environment: Environment = "dev"
    log_level: LogLevel = "INFO"
    log_json: bool | None = Field(
        default=None,
        description="Force JSON logs on/off. When unset, JSON is used outside 'dev'.",
    )
    timezone: str = "America/Lima"

    http: HttpCfg = Field(default_factory=HttpCfg)
    app_db: AppDbCfg = Field(default_factory=AppDbCfg)
    redis: RedisCfg = Field(default_factory=RedisCfg)
    odoo: OdooCfg = Field(default_factory=OdooCfg)
    mail: MailCfg = Field(default_factory=MailCfg)
    llm: LlmCfg = Field(default_factory=LlmCfg)
    langfuse: LangfuseCfg = Field(default_factory=LangfuseCfg)
    events: EventsCfg = Field(default_factory=EventsCfg)
    mail_sync: MailSyncCfg = Field(default_factory=MailSyncCfg)
    scheduler: SchedulerCfg = Field(default_factory=SchedulerCfg)
    agents: AgentsCfg = Field(default_factory=AgentsCfg)
    a2a: A2aCfg = Field(default_factory=A2aCfg)
    director: DirectorCfg = Field(default_factory=DirectorCfg)
    planning: PlanningCfg = Field(default_factory=PlanningCfg)
    ui: UiCfg = Field(default_factory=UiCfg)
    supplier_comms: SupplierCommsCfg = Field(default_factory=SupplierCommsCfg)

    @property
    def a2a_token(self) -> str:
        return self.a2a.token.get_secret_value() or self.events.signing_secret.get_secret_value()

    def __init__(self, **values: Any) -> None:
        # pydantic-settings reads .env only for its own SC__ fields. Provider API
        # keys (DEEPSEEK_API_KEY, OPENAI_API_KEY) are looked up by name in the
        # environment by sc_core.llm.registry, so on the host they must be
        # exported from the same file. Docker passes env_file, so this is a no-op there.
        env_file = values.get("_env_file", ".env")
        if env_file:
            load_env_file(env_file)
        super().__init__(**values)

    @property
    def is_dev(self) -> bool:
        return self.environment == "dev"

    @property
    def use_json_logs(self) -> bool:
        return self.log_json if self.log_json is not None else not self.is_dev


def load_env_file(path: str | PathLike[str] = ".env") -> None:
    """Export the non-``SC__`` entries of ``path`` (provider API keys) into ``os.environ``.

    ``SC__*`` values are left to pydantic-settings so ``Settings(_env_file=None)``
    keeps isolating tests from the developer's ``.env``. Existing variables win.
    """
    for key, value in dotenv_values(path).items():
        if value is not None and not key.startswith("SC__") and key not in os.environ:
            os.environ[key] = value


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Return the process-wide settings, built once from the environment."""
    return Settings()


def reset_settings_cache() -> None:
    """Forget the cached settings. Intended for tests that mutate the environment."""
    get_settings.cache_clear()
