/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Approvals */
        get: operations["list_approvals_api_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Approval */
        get: operations["get_approval_api_approvals__approval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/{approval_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Approval */
        post: operations["resolve_approval_api_approvals__approval_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_api_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exceptions Board */
        get: operations["exceptions_board_api_exceptions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exceptions/{kind}/{po_name}/act": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Act Now
         * @description Run the follow-up step for this order now (a model call and an email or an escalation).
         */
        post: operations["act_now_api_exceptions__kind___po_name__act_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planning/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Planning Runs */
        get: operations["list_planning_runs_api_planning_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planning/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Planning Run */
        get: operations["get_planning_run_api_planning_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planning/runs/{run_id}/what-if": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * What If
         * @description Recompute one line with other parameters; nothing is written anywhere.
         */
        post: operations["what_if_api_planning_runs__run_id__what_if_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/scheduler": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scheduler Runs */
        get: operations["list_scheduler_runs_api_runs_scheduler_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        /** Put Settings */
        put: operations["put_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings History */
        get: operations["settings_history_api_settings_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: operations["stream_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Accepted */
        Accepted: {
            /** Accepted */
            accepted: boolean;
            /**
             * Dispatched
             * @default false
             */
            dispatched: boolean;
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
        };
        /** ActResponse */
        ActResponse: {
            /** Accepted */
            accepted: boolean;
            /** Message */
            message: string;
            /** Po Name */
            po_name: string;
        };
        /** AgentRunView */
        AgentRunView: {
            /** Agent */
            agent: string;
            /** Case Id */
            case_id?: string | null;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Llm Calls
             * @default 0
             */
            llm_calls: number;
            /** Model */
            model?: string | null;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /** Po Id */
            po_id?: number | null;
            /** Po Name */
            po_name?: string | null;
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
            /** Summary */
            summary?: string | null;
            /** Trace Url */
            trace_url?: string | null;
        };
        /** ApprovalLinks */
        ApprovalLinks: {
            /** Odoo */
            odoo?: string | null;
            /** Order */
            order?: string | null;
            /** Outlook */
            outlook?: string | null;
            /** Trace */
            trace?: string | null;
        };
        /** ApprovalView */
        ApprovalView: {
            /** Case Id */
            case_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** @default {} */
            links: components["schemas"]["ApprovalLinks"];
            /**
             * Payload
             * @default {}
             */
            payload: {
                [key: string]: unknown;
            };
            /** Po Id */
            po_id?: number | null;
            /** Po Name */
            po_name?: string | null;
            /** Reason */
            reason?: string | null;
            /** Requested By */
            requested_by?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /** Resolved By */
            resolved_by?: string | null;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /** Thread Id */
            thread_id?: string | null;
            /**
             * Why
             * @description rule or model reasoning behind it
             */
            why?: string | null;
        };
        /** CaseDetail */
        CaseDetail: {
            case: components["schemas"]["CaseView"];
            /** Events */
            events: components["schemas"]["CaseEventView"][];
            /** Runs */
            runs: components["schemas"]["AgentRunView"][];
        };
        /** CaseEventView */
        CaseEventView: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** CaseView */
        CaseView: {
            /** Agent */
            agent?: string | null;
            /** Case Id */
            case_id: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "rfq" | "eta" | "inbound" | "unlinked" | "receipt" | "planning" | "invoice";
            /** Next Action At */
            next_action_at?: string | null;
            /** Partner Id */
            partner_id?: number | null;
            /** Po Name */
            po_name?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "awaiting_approval" | "done" | "rejected" | "failed" | "escalated";
            /** Summary */
            summary?: string | null;
            /** Trace Url */
            trace_url?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CheckResult */
        CheckResult: {
            /** Critical */
            critical: boolean;
            /** Detail */
            detail?: string | null;
            /** Duration Ms */
            duration_ms: number;
            /** Name */
            name: string;
            status: components["schemas"]["CheckStatus"];
        };
        /**
         * CheckStatus
         * @enum {string}
         */
        CheckStatus: "ok" | "fail";
        /** DiscoveryResponse */
        DiscoveryResponse: {
            /** Core Version */
            core_version: string;
            /** Environment */
            environment: string;
            /** Routes */
            routes: components["schemas"]["RouteInfo"][];
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** ExceptionItem */
        ExceptionItem: {
            /** Approval Id */
            approval_id?: number | null;
            /**
             * Can Act
             * @default false
             */
            can_act: boolean;
            /** Case Id */
            case_id?: string | null;
            /**
             * Days
             * @default 0
             */
            days: number;
            /** Detail */
            detail: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "late_po" | "rfq_no_reply" | "unlinked_mail" | "failed_run" | "stale_approval";
            /** Next Action */
            next_action?: string | null;
            /** Next Action At */
            next_action_at?: string | null;
            /** Odoo Url */
            odoo_url?: string | null;
            /** Partner Id */
            partner_id?: number | null;
            /** Po Id */
            po_id?: number | null;
            /** Po Name */
            po_name?: string | null;
            /** Title */
            title: string;
        };
        /** ExceptionsBoard */
        ExceptionsBoard: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Failed Runs
             * @default []
             */
            failed_runs: components["schemas"]["ExceptionItem"][];
            /**
             * Late Pos
             * @default []
             */
            late_pos: components["schemas"]["ExceptionItem"][];
            /**
             * Rfqs No Reply
             * @default []
             */
            rfqs_no_reply: components["schemas"]["ExceptionItem"][];
            /**
             * Stale Approvals
             * @default []
             */
            stale_approvals: components["schemas"]["ExceptionItem"][];
            /**
             * Unlinked Mails
             * @default []
             */
            unlinked_mails: components["schemas"]["ExceptionItem"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthReport */
        HealthReport: {
            /** Checks */
            checks: components["schemas"]["CheckResult"][];
            /** Service */
            service: string;
            status: components["schemas"]["OverallStatus"];
            /** Version */
            version: string;
        };
        /** LiveResponse */
        LiveResponse: {
            /** Service */
            service: string;
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Version */
            version: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "approver" | "admin";
            /** Token */
            token: string;
        };
        /**
         * OverallStatus
         * @enum {string}
         */
        OverallStatus: "ok" | "degraded" | "fail";
        /** PlanningLineRow */
        PlanningLineRow: {
            /** Accepted */
            accepted?: boolean | null;
            /** Applied */
            applied?: {
                [key: string]: unknown;
            } | null;
            /** Applied At */
            applied_at?: string | null;
            line: components["schemas"]["ReplenishmentLine"];
        };
        /**
         * PlanningOverrides
         * @description Parameters a planner may try in a ``what_if`` (no writes) or force in a review.
         */
        PlanningOverrides: {
            /** Lead Time Days */
            lead_time_days?: number | null;
            /** Max Coverage Days */
            max_coverage_days?: number | null;
            /** Review Period Days */
            review_period_days?: number | null;
            /** Service Level */
            service_level?: number | null;
        };
        /** PlanningRunDetail */
        PlanningRunDetail: {
            /** Lines */
            lines: components["schemas"]["PlanningLineRow"][];
            run: components["schemas"]["PlanningRunRow"];
        };
        /** PlanningRunRow */
        PlanningRunRow: {
            /** Approval Id */
            approval_id?: number | null;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Case Id */
            case_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Kind */
            kind: string;
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Summary */
            summary?: string | null;
            /**
             * Totals
             * @default {}
             */
            totals: {
                [key: string]: number;
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Warehouse Id */
            warehouse_id: number;
        };
        /**
         * Principal
         * @description Who is calling, as decoded from the token.
         */
        Principal: {
            /** Email */
            email: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "approver" | "admin";
        };
        /** ReplenishmentLine */
        ReplenishmentLine: {
            /** Abc Class */
            abc_class: string;
            /**
             * Action
             * @default none
             * @enum {string}
             */
            action: "update_rule" | "create_rfq" | "update_rule_and_rfq" | "hold" | "manual_review" | "none";
            /** Coverage Days */
            coverage_days?: number | null;
            /** Currency */
            currency?: string | null;
            /** Current Max */
            current_max?: number | null;
            /** Current Min */
            current_min?: number | null;
            /** Exception */
            exception?: ("stockout_risk" | "overstock" | "lead_time_drift" | "no_supplier" | "negative_position" | "no_history") | null;
            /** Explanation */
            explanation?: string | null;
            /** Forecast Daily */
            forecast_daily: number;
            /** Forecast Method */
            forecast_method: string;
            /** History Periods */
            history_periods: number;
            /** Incoming */
            incoming: number;
            /** Lead Time Days */
            lead_time_days: number;
            /**
             * Line Id
             * @description <run_id>:<product_id>
             */
            line_id: string;
            /** Mape */
            mape?: number | null;
            /**
             * Moq
             * @default 0
             */
            moq: number;
            /** On Hand */
            on_hand: number;
            /** Order Qty */
            order_qty: number;
            /** Order Up To */
            order_up_to: number;
            /**
             * Position
             * @description on hand - reserved + incoming
             */
            position: number;
            /** Product Id */
            product_id: number;
            /**
             * Product Name
             * @default
             */
            product_name: string;
            /** Product Ref */
            product_ref: string;
            /** Proposed Max */
            proposed_max: number;
            /** Proposed Min */
            proposed_min: number;
            /**
             * Reserved
             * @default 0
             */
            reserved: number;
            /** Review Period Days */
            review_period_days: number;
            /** Rop */
            rop: number;
            /** Service Level */
            service_level: number;
            /** Sigma Daily */
            sigma_daily: number;
            /** Sigma Lead Time Days */
            sigma_lead_time_days: number;
            /** Ss */
            ss: number;
            /** Supplier Id */
            supplier_id?: number | null;
            /** Supplier Name */
            supplier_name?: string | null;
            /** Unit Price */
            unit_price?: number | null;
            /** Wape */
            wape?: number | null;
            /** Warehouse Id */
            warehouse_id: number;
        };
        /** ResolveRequest */
        ResolveRequest: {
            /**
             * Edited Payload
             * @description per kind: EmailEdits, ChangeEdits or PlanEdits
             */
            edited_payload?: {
                [key: string]: unknown;
            } | null;
            /** Reason */
            reason?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "approved" | "rejected";
        };
        /** ResolveResponse */
        ResolveResponse: {
            /** Callback Status */
            callback_status?: string | null;
            /** Id */
            id: number;
            /** Resolved By */
            resolved_by: string;
            /** Status */
            status: string;
        };
        /** RouteInfo */
        RouteInfo: {
            /** Methods */
            methods: string[];
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /** RuntimeSettings */
        RuntimeSettings: {
            /**
             * Approval Expire Days
             * @default 7
             */
            approval_expire_days: number;
            /**
             * Approval Stale Days
             * @default 2
             */
            approval_stale_days: number;
            /**
             * Auto Send Partner Ids
             * @default []
             */
            auto_send_partner_ids: number[];
            /**
             * Max Actions Per Run
             * @default 20
             */
            max_actions_per_run: number;
            /**
             * Model By Agent
             * @description agent name -> model name from the registry
             */
            model_by_agent?: {
                [key: string]: string;
            };
            /** Planning Max Coverage Days */
            planning_max_coverage_days?: number | null;
            /** Planning Review Period Days */
            planning_review_period_days?: number | null;
            /** Planning Service Level */
            planning_service_level?: number | null;
            /**
             * Po Eta Request Before Days
             * @default 5
             */
            po_eta_request_before_days: number;
            /**
             * Po Late Days
             * @default [
             *       1,
             *       4
             *     ]
             */
            po_late_days: number[];
            /**
             * Rfq No Reply Days
             * @default [
             *       3,
             *       7
             *     ]
             */
            rfq_no_reply_days: number[];
        };
        /** SchedulerRunView */
        SchedulerRunView: {
            /** Cron */
            cron?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Http Status */
            http_status?: number | null;
            /** Job Id */
            job_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Summary */
            summary?: string | null;
            /** Trigger */
            trigger: string;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Note */
            note?: string | null;
            settings: components["schemas"]["RuntimeSettings"];
        };
        /** SettingsVersion */
        SettingsVersion: {
            /**
             * Changed At
             * Format: date-time
             */
            changed_at: string;
            /** Changed By */
            changed_by: string;
            /** Note */
            note?: string | null;
            settings: components["schemas"]["RuntimeSettings"];
            /** Version */
            version: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WhatIfRequest */
        WhatIfRequest: {
            /** Line Id */
            line_id: string;
            overrides: components["schemas"]["PlanningOverrides"];
        };
        /** WhatIfResponse */
        WhatIfResponse: {
            baseline: components["schemas"]["ReplenishmentLine"];
            /** Run Id */
            run_id: string;
            simulated: components["schemas"]["ReplenishmentLine"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_approvals_api_approvals_get: {
        parameters: {
            query?: {
                status?: "pending" | "approved" | "rejected" | "expired" | "all";
                kind?: string | null;
                po?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_api_approvals__approval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_approval_api_approvals__approval_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Principal"];
                };
            };
        };
    };
    list_cases_api_cases_get: {
        parameters: {
            query?: {
                status?: ("open" | "awaiting_approval" | "done" | "rejected" | "failed" | "escalated") | null;
                po?: string | null;
                kind?: ("rfq" | "eta" | "inbound" | "unlinked" | "receipt" | "planning" | "invoice") | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_api_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exceptions_board_api_exceptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionsBoard"];
                };
            };
        };
    };
    act_now_api_exceptions__kind___po_name__act_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "late_po" | "rfq_no_reply" | "unlinked_mail" | "failed_run" | "stale_approval";
                po_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_planning_runs_api_planning_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanningRunRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_planning_run_api_planning_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanningRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    what_if_api_planning_runs__run_id__what_if_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatIfRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatIfResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                agent?: string | null;
                model?: string | null;
                status?: string | null;
                since?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scheduler_runs_api_runs_scheduler_get: {
        parameters: {
            query?: {
                job?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerRunView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsVersion"];
                };
            };
        };
    };
    put_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsVersion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings_history_api_settings_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsVersion"][];
                };
            };
        };
    };
    stream_api_stream_get: {
        parameters: {
            query: {
                /** @description the session token (EventSource cannot send headers) */
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
